<?php
$app->view()->addCSS(WEB_ROOT . "/themes/Eventsd" . "/css/ubuntu.css");
$app->view()->addCSS(WEB_ROOT . "/themes/Eventsd" . "/css/unity.css");
$app->view()->addCSS(WEB_ROOT . "/themes/Eventsd" . "/css/events-table.css");
$app->view()->addCSS(WEB_ROOT . "/themes/Eventsd" . "/css/workflow.css");
$app->view()->addJS(WEB_ROOT . "/themes/Eventsd" . "/js/workflow.js");
$app->view()->addJS(WEB_ROOT . "/themes/Eventsd" . "/highcharts/js/highcharts.js");
$app->view()->addJS(WEB_ROOT . "/themes/Eventsd" . "/highcharts/js/highcharts-more.js");
//$app->view()->addJS(WEB_ROOT . "/themes/Eventsd" . "/highcharts/js/modules/exporting.js");
