
<table class="table table-striped events-list">
  <thead>
    <tr>
      <th>System</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>UDP Service:</td>
      <td><?php echo $udp; ?></td>
    </tr>
    <tr>
      <td>Node JS:</td>
      <td><?php echo $nodejs; ?></td>
    </tr>
  </tbody>
</table>

<div class="row">
  <h1>Load & Events Rate</h1>
  <div class="col-md-4">
    <div id="rate-container-second" style="width: 100%; height: 250px; margin: 0 auto"></div>
  </div>
  <div class="col-md-4">
    <div id="rate-container-minute" style="width: 100%; height: 250px; margin: 0 auto"></div>
  </div>
</div>

