<head>

  <!-- start: Meta -->
  <meta charset="utf-8">
  <title><?php echo $this->getSiteTitle(); ?></title>
  <meta name="description" content="<?php echo $this->getSiteTitle(); ?>">
  <meta name="author" content="Matthew Baggett <matthew@fouroneone.us>">
  <!-- end: Meta -->

  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- start: CSS -->
    <?php foreach($this->getCSS() as $css): ?>
        <link id="base-style" href="<?php echo $this->url($css);?>" rel="stylesheet">
    <?php endforeach; ?>
  <!-- end: CSS -->

  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <script type="text/javascript" src="https://www.google.com/jsapi"></script>


  <!-- start: Favicon -->
  <link rel="shortcut icon" href="<?php echo $this->url("img/favicon.ico");?>">
  <!-- end: Favicon -->

    <script>
        var app_root = '<?php echo $this->url("/"); ?>';
    </script>


</head>