<?php
$this->addJS("themes/Base/js/realtimeui.js");

?>
<table class="table table-striped events-list">
  <thead>
    <tr>
      <th class="application">Application</th>
      <th class="event">Event</th>
      <th class="value">Value</th>
      <th class="host">Host</th>
      <th class="time">Time</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($occurrences as $occurrence): ?>
      <?php /* @var $occurrence \Eventsd\Models\Occurrence */ ?>
      <tr>
        <td class="application"><?php echo $occurrence->get_application() instanceof \Eventsd\Models\Application? $occurrence->get_application()->name : 'No Application Set'; ?></td>
        <td class="event"><?php echo $occurrence->event; ?></td>
        <td class="value">
          <?php if($occurrence->get_value() == ''): ?>
            --
          <?php //elseif($occurrence->value_is_json()): ?>
            <?php //Kint::dump(json_decode($occurrence->get_value())); ?>
          <?php else: ?>
            <?php echo $occurrence->get_value(); ?>
          <?php endif; ?>
        </td>
        <td class="host"><?php echo $occurrence->hostname; ?></td>
        <td class="time"><?php echo $occurrence->local_time; ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
