<?php
$this->addJS("themes/Base/js/realtimeui.js");

?>
<table class="table table-striped events-list">
  <thead>
    <tr>
      <th>Application</th>
      <th>Event</th>
      <th>Value</th>
      <th>Host</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($occurrences as $occurrence): ?>
      <?php /* @var $occurrence \Eventsd\Models\Occurrence */ ?>
      <tr>
        <td><?php echo $occurrence->get_api_key() instanceof \Eventsd\Models\ApiKey ? $occurrence->get_api_key()->get_application()->name : 'No API Key'; ?></td>
        <td><?php echo $occurrence->event; ?></td>
        <td>
          <?php if($occurrence->get_value() == ''): ?>
            --
          <?php //elseif($occurrence->value_is_json()): ?>
            <?php //Kint::dump(json_decode($occurrence->get_value())); ?>
          <?php else: ?>
            <?php echo $occurrence->get_value(); ?>
          <?php endif; ?>
        </td>
        <td><?php echo $occurrence->hostname; ?></td>
        <td><?php echo $occurrence->local_time; ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
