<h1>New Workflow</h1>
<div class="col-md-12">
  <div class="col-md-2">
    <ul class="events">
      <?php foreach($events as $event): ?>
        <?php /* @var $event \Eventsd\Models\Occurrence */ ?>
        <li class="event">
          <div class="name"><span><?php echo $event->event; ?></span></div>
          <ul class="properties">
            <?php foreach($event->get_properties() as $property): ?>
              <li><?php echo $property; ?></li>
            <?php endforeach; ?>
          </ul>
        </li>
      <?php endforeach; ?>
    </ul>
  </div>
</div>