<h1>My Workflows</h1>
<div class="row">
  <div class="col-md-12">
    <a href="<?php echo $this->url("workflow/create"); ?>" class="btn btn-primary btn-sm">
      <span class="glyphicon glyphicon-plus"></span> Create New Workflow
    </a>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Workflow</th>
        <th>Events Effected</th>
        <th>Triggered Last</th>
        <th>Triggered Count</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Name Here</td>
        <td>Event, List, Here</td>
        <td>Never</td>
        <td>0</td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
