<div class="page-header">
  <h1><?php echo $this->t("Add new External Account", array(':sitename' => $this->getSiteTitle(false))); ?></h1>
  <div class="row">
    <?php require("sidebar.phtml"); ?>
    <div class="col-md-9">
      <div class="well bs-component">
        <form class="form-horizontal" action="<?php echo $this->url("options/external-accounts/connect"); ?>" method="post">
          <fieldset>
            <legend>New External Account</legend>
            <!--<div class="form-group">
              <label for="inputEmail" class="col-lg-2 control-label">Alias</label>
              <div class="col-lg-10">
                <input type="text" class="form-control" id="alias" placeholder="Alias for this External Account">
              </div>
            </div>-->
            <div class="form-group">
              <label for="select" class="col-lg-2 control-label">Service</label>
              <div class="col-lg-10">
                <select class="form-control" id="service" name="service">
                  <option>Please select a Remote Service to add.</option>
                  <?php foreach($services as $service): ?>
                    <option value="<?php echo $service->external_account_type_id; ?>"><?php echo $service->name; ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary">Jump!</button>
              </div>
            </div>
          </fieldset>
        </form>
    </div>
  </div>
</div>