<div class="page-header">
  <h1><?php echo $this->t("My External Accounts", array(':sitename' => $this->getSiteTitle(false))); ?></h1>
  <div class="row">
    <?php require("sidebar.phtml"); ?>
    <div class="col-md-9">
      <a href="<?php echo $this->url("options/external-accounts/new"); ?>" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>Add External Account</a>
      <table class="table table-striped table-hover ">
        <thead>
        <tr>
          <th>Operator</th>
          <th>Username/ID</th>
          <th>Input Sync</th>
          <th>Output Sync</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
          <?php foreach($accounts as $account): ?>
            <tr>
              <td><?=$account->get_type()->name; ?></td>
              <td><?=$account->get_email(); ?> (<?=$account->get_firstname() . "&nbsp;" . $account->get_lastname(); ?>)</td>
              <td>--</td>
              <td>--</td>
              <td>
                <?php if(method_exists($account, 'check_for_events')): ?>
                  <a href="<?=$this->url("options/external-accounts/check-for-events/{$account->external_account_id}"); ?>" class="btn btn-primary btn-sm">Check Events</a>
                <?php endif; ?>
                <a href="<?=$this->url("options/external-accounts/remove/{$account->external_account_id}"); ?>" class="btn btn-danger btn-sm">Remove</a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
</div>