<div class="page-header">
  <h1><?php echo $this->t("New Webhook", array(':sitename' => $this->getSiteTitle(false))); ?></h1>
  <div class="row">
    <?php require("sidebar.phtml"); ?>
    <div class="col-md-9">
      <div class="well bs-component">
        <form class="form-horizontal" action="<?php echo $this->url("options/webhooks/new"); ?>" method="post">
          <fieldset>
            <legend>New Webhook</legend>
            <div class="form-group">
              <label for="select" class="col-lg-2 control-label">Name for Webhook</label>
              <div class="col-lg-10">
                <input class="form-control" id="service" name="name"/>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary">Create!</button>
              </div>
            </div>
          </fieldset>
        </form>
    </div>
  </div>
</div>