<div class="col-md-3">
  <div class="list-group">
    <a class="list-group-item <?php echo $_SERVER['REQUEST_URI'] == '/options'?'active':''; ?>" href="<?php echo $this->url("options"); ?>">My Gone.io Account.</a>
    <a class="list-group-item <?php echo $_SERVER['REQUEST_URI'] == '/options/external-accounts'?'active':''; ?>" href="<?php echo $this->url("options/external-accounts"); ?>">My External Accounts.</a>
    <a class="list-group-item <?php echo $_SERVER['REQUEST_URI'] == '/options/privacy'?'active':''; ?>" href="<?php echo $this->url("options/privacy"); ?>">My Privacy Options.</a>
  </div>
</div>

