<div class="page-header">
  <h1><?php echo $this->t("My Webhooks", array(':sitename' => $this->getSiteTitle(false))); ?></h1>
  <div class="row">
    <?php require("sidebar.phtml"); ?>
    <div class="col-md-9">
      <a href="<?php echo $this->url("options/webhooks/new"); ?>" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>New Webhook</a>
      <table class="table table-striped table-hover ">
        <thead>
        <tr>
          <th>Webhook name</th>
          <th>Application</th>
          <th>URL</th>
          <th>Last Triggered</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
          <?php foreach($webhooks as $webhook): ?>
            <?php /* @var $webhook \EventsdWeb\Models\ExternalWebhook */ ?>
            <tr>
              <td><?php echo $webhook->name; ?></td>
              <td><?php echo $webhook->get_application() instanceof \Eventsd\Models\Application?$webhook->get_application()->name:'--'; ?></td>
              <td>http://intervent.io/webhook/<?php echo $webhook->key; ?></td>
              <td><?php echo $webhook->get_last_event() instanceof \Eventsd\Models\Occurrence?$webhook->get_last_event()->local_time:'Never Triggered';?></td>
              <td>
                <a href="<?=$this->url("options/webhooks/remove/{$webhook->external_webhook_id}"); ?>" class="btn btn-danger btn-sm">Remove</a>
              </td>

            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
</div>